name: Release qzone-history

permissions:
  id-token: write
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin] # Windows, Linux, macOS
        goarch: [amd64, arm64]          # 64-bit architectures
        go-version: ['1.23.0']          # Go 版本

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build qzone-history
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o qzone-history-${{ matrix.goos }}-${{ matrix.goarch }} cmd/main.go

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qzone-history-${{ matrix.goos }}-${{ matrix.goarch }}
          path: qzone-history-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release for qzone-history
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*  # 选择所有已下载的二进制文件
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
